### oh-my-zsh config ###
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

# history timestamps
HIST_STAMPS="yyyy-mm-dd"

# oh-my-zsh plugins
plugins=(git python pip nvm colored-man-pages docker)

source $ZSH/oh-my-zsh.sh

source ~/.dotfiles/zsh/variables.zsh

# $PATH
source ~/.dotfiles/zsh/path.zsh

### EDITOR (vim) ###
export VISUAL="vim"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

### THE FUCK  ###
eval $(thefuck --alias)

### ALIASES ###
source ~/.dotfiles/zsh/alias.zsh

# nvm
source ~/.dotfiles/zsh/nvm.zsh

# pyenv
source ~/.dotfiles/zsh/pyenv.zsh

# phpenv
source ~/.dotfiles/zsh/phpenv.zsh

### LOCAL Environment ###
if [ -f ~/.dotfiles/zsh/local.zsh ]; then
	source ~/.dotfiles/zsh/local.zsh
fi

